spring:
  application:
    name: stock-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      discovery:
        enabled: true
        service-id: ${CLOUD_SERVICE_ID}
  docker:
    compose:
      lifecycle-management: start_only
eureka:
  instance:
    prefer-ip-address: false
    hostname: ${EUREKA_HOSTNAME}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

rabbit:
  stock:
    exchange: athenhub.stock.exchange
    registered:
      routing-key: athenhub.stock.registered
      queue: athenhub.stock.registered.queue
    decreased:
      routing-key: athenhub.stock.decreased
      queue: athenhub.stock.decreased.queue
    decrease-fail:
      routing-key: athenhub.stock.decrease.fail
      queue: athenhub.stock.decreased.fail.queue
  order:
    exchange: athenhub.order.exchange
    created:
      routing-key: athenhub.order.created
      queue: athenhub.order.created.queue
