spring:
  cloud:
    config:
      enabled: false
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_schema:
    hibernate:
      ddl-auto: create
    open-in-view: false
    generate-ddl: true

eureka:
  client:
    enabled: false

rabbit:
  stock:
    exchange: stock.exchange
    registered:
      routing-key: stock.registered
      queue: stock.registered.queue
    decreased:
      routing-key: stock.decreased
      queue: stock.decreased.queue
  order:
    exchange: order.exchange
    created:
      routing-key: order.created
      queue: order.created.queue

