spring:
  config:
    activate:
      on-profile: local
  cloud:
    config:
      enabled: false
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_schema:
    hibernate:
      ddl-auto: create
    open-in-view: false
    generate-ddl: true

eureka:
  client:
    enabled: false

rabbit:
  stock:
    exchange: stock.exchange                # 정상 이벤트 전용 Exchange
    dlq-exchange: stock.dlq.exchange        # DLQ 전용 Exchange

    registered:
      routing-key: stock.registered
      queue: stock.registered.queue

    decrease:
      routing-key: stock.decrease
      queue: stock.decrease.queue

    decrease-retry:
      routing-key: stock.decrease.retry
      queue: stock.decrease.retry.queue
      ttl: 500

    decrease-dead:
      routing-key: stock.decrease.dead
      queue: stock.decrease.dead.queue

    decrease-success:
      routing-key: stock.decrease.success
      queue: stock.decrease.success.queue
  order:
    exchange: order.exchange
    created:
      routing-key: order.created
      queue: order.created.queue
