#spring:
#  application:
#    name: stock-service
#  config:
#    import: 'optional:configserver:'
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        service-id: ${CLOUD_SERVICE_ID}
#  docker:
#    compose:
#      lifecycle-management: start_only
#eureka:
#  instance:
#    prefer-ip-address: false
#    hostname: ${EUREKA_HOSTNAME}
#
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: ${EUREKA_SERVICE_URL}
#
#  rabbitmq:
#    host: localhost                 # RabbitMQ 브로커의 호스트명 또는 IP. 로컬 테스트 시 'localhost' 사용.
#    port: 5672                      # AMQP 포트(기본 5672). 브로커가 다른 포트를 쓰면 해당 포트로 설정.
#    username: ${RABBITMQ_USERNAME}                # 연결에 사용할 사용자 계정명. 운영 환경에서는 비밀 관리 도구로 보관 권장.
#    password: ${RABBITMQ_PASSWORD}            # 사용자 비밀번호. 절대 코드/레포지토리에 평문 저장 금지(환경변수/Vault 사용 권장).
#rabbit:
#  stock:
#    exchange: stock.exchange
#    queue: stock.queue
#    routing-key: stock.*
#
